### ISSUE TITLE
Push error in POET

### ISSUE THREAD

**Issue by omehes** [openstax/poet#100]
I installed the latest extension in poet editor-0.0.0-dev-43edcf1.vsix but it’s causing Push error. I tried reloading, etc but the error is always there. Then I installed the second latest extension editor-0.0.0-dev-b35abc4.vsix and no Push error. 

As discussed:
Ripal: I believe that error is coming from here, but it’s not immediately obvious to me what the root issue might be. It’s probably worth creating a bug to investigate further, though. :bug:

Phil:
that's my fault! There's a 2-line fix in the image autocompletion work: https://github.com/openstax/poet/commit/041183e619aefd04ef911f31f3a77cffcb2790c5
(and another fix for the underlying "why try to read a directory") (edited) 

![1EAC9DB5-7383-4EF5-A76E-EFB7076D9388.jpeg](https://images.zenhubusercontent.com/5bc8d1f2fe40ab78d94e65fb/3d29a00f-a0bc-4bc8-807c-c5ee133dbb7c)

**Comment by philschatz** [comment]
This bug was introduced in #96 and should be fixed in #95 which was just merged.

**Comment by omehes** [comment]
tested and retested with editor-0.0.0-dev-6db00dd.vsix
fixed
